In [18]:
import numpy as np


In [3]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
np.zeros(5) #1 solo numero para un arreglo
np.zeros([5,5]) #1 lista o tupla para una matriz de n dimensiones
np.zeros((5,5))
#np.zeros([1,2,2,2,2,2])
np.zeros([1000,200])
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [11]:
np.ones(7)
np.ones((1,2,3,4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [14]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:
np.arange(5) #1 parametro, #de elementos

array([0, 1, 2, 3, 4])

In [19]:
np.arange(4,21) # [4, 20]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
np.arange(-12,1) # [-12, 1[

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [21]:
np.arange(0,20,2) #del 0 a 20 en intervalo de 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
np.zeros(20).reshape(2,5,2).reshape(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [28]:
len(np.ones(12))

12

In [29]:
len(np.ones(12).reshape(4,3))

3

In [30]:
np.ones(12).reshape(4,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.ones(12).reshape(4,3).shape

(4, 3)

In [33]:
arreglo = np.ones(12).reshape(4,3)

In [34]:
len(arreglo)

4

In [35]:
len(arreglo[0])

3

In [36]:
np.arange(12).reshape(4,3)[1][2]

5

In [37]:
np.arange(12).reshape(4,3)[1,2]

5

In [38]:
np.array([1, 7, 12, 16]).reshape(2,2)

array([[ 1,  7],
       [12, 16]])

In [39]:
a = np.array([10,10,10])

In [45]:
b = np.array([5,5,5])

In [46]:
a + b #suma de array

array([15, 15, 15])

In [47]:
a - b #resta de array

array([5, 5, 5])

In [48]:
a + 7 #suma valor

array([17, 17, 17])

In [50]:
a - 8 #resta valor

array([2, 2, 2])

In [54]:
a * b #multiplicacion arrays

array([50, 50, 50])

In [52]:
a * 3 #multiplicacion valor

array([30, 30, 30])

In [53]:
# division arrays
a / b

array([2., 2., 2.])

In [55]:
#division valor
a / 2

array([5., 5., 5.])

In [56]:
#modulo
a % 3

array([1, 1, 1], dtype=int32)

In [57]:
#modulo
a % b

array([0, 0, 0], dtype=int32)

In [58]:
muestra = np.arange(20).reshape(5,2,2)

In [59]:
muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [100]:
respuesta_glucosa = (muestra > 5) & (muestra < 14) & (muestra % 2 == 0)

In [101]:
respuesta_glucosa

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True, False]],

       [[ True, False],
        [ True, False]],

       [[ True, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [102]:
muestra[respuesta_glucosa]

array([ 6,  8, 10, 12])

In [103]:
# mayores a 5 glucosa y menores a 14 y que sean pares
muestra[respuesta_glucosa]


array([ 6,  8, 10, 12])

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False])

NameError: name 'np' is not defined

NameError: name 'np' is not defined

NameError: name 'np' is not defined

NameError: name 'np' is not defined

NameError: name 'np' is not defined

NameError: name 'np' is not defined

NameError: name 'np' is not defined

NameError: name 'np' is not defined

NameError: name 'np' is not defined

NameError: name 'np' is not defined

NameError: name 'np' is not defined

NameError: name 'np' is not defined

NameError: name 'np' is not defined

In [21]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [26]:
B = np.arange(4).reshape((2,2))
B

array([[0, 1],
       [2, 3]])

In [27]:
np.dot(A,B)

array([[ 2,  3],
       [ 6, 11]])

In [28]:
np.dot(B,A)

array([[ 2,  3],
       [ 6, 11]])

In [30]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
arreglo_doce.sum()

66

In [32]:
arreglo_doce.min()

0

In [33]:
arreglo_doce.max()

11

In [34]:
arreglo_doce[5:].sum()

56

In [35]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [36]:
arreglo_doce.reshape(3,2,2).sum()

66

In [37]:
arreglo_doce.reshape(3,2,2).sum(axis = 0)

array([[12, 15],
       [18, 21]])

In [38]:
arreglo_doce.reshape(3,2,2).sum(axis = 1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [40]:
arreglo_doce.reshape(3,2,2).sum(axis = 2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])