In [1]:
import numpy as np

In [2]:
arreglo_grados = np.array([0,30,45,60,90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [3]:
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [4]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [5]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [6]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [9]:
numero_random = np.random.randint(
    11 # [0,11[
)
numero_random

7

In [11]:
numero_random_negativo = np.random.randint(
    -9,2 # [-9,2[
)
numero_random_negativo

-5

In [13]:
arreglo_random = np.random.randint(
    10,
    20,
    8
)
arreglo_random

array([12, 14, 15, 14, 18, 10, 15, 19])

In [17]:
np.random.rand(9) #9 elementos


array([0.42348583, 0.14317829, 0.48028319, 0.60660156, 0.54827408,
       0.25916019, 0.2355443 , 0.81171809, 0.70126691])

In [16]:
np.random.rand(3,2) #6 elementos (3x2 dimensiones)

array([[0.10011865, 0.08809941],
       [0.36141683, 0.90903438],
       [0.03019011, 0.90447328]])

In [18]:
np.average(arreglo_random)

14.625

In [19]:
np.mean(arreglo_random)

14.625

In [20]:
np.median(arreglo_random)

14.5

In [21]:
np.std(arreglo_random)

2.7357585785299112

In [22]:
np.var(arreglo_random)

7.484375

In [23]:
arreglo_random.mean()

14.625